apiVersion: apps/v1
kind: Deployment
metadata:
  name: gramophone-frontend-deployment
  namespace: default
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: gramophone-frontend
  template: 
    metadata:
      labels:
        app: gramophone-frontend
    spec:
      dnsPolicy: Default
      containers:
        - name: gramophone-frontend
          image: gramophone/gramophone_frontend:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /app/logs/
      volumes:
      - name: data
        hostPath:
          path: /home/docker/logs
---
apiVersion: v1
kind: Service
metadata:
  name: gramophone-frontend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: gramophone-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort : 12700
