pipeline {
    // The “agent” section configures on which nodes the pipeline can be run.
    // Specifying “agent any” means that Jenkins will run the job on any of the
    // available nodes.
	agent any

    stages {
        stage('Git Pull') {
            steps {
                // Get code from a GitHub repository
                // Make sure to add your own git url and credentialsId
				git url: 'https://github.com/delta7-138/Gramophone.git'
		    }
        }
        // stage('Build and Test - Backend') {
        //     steps {
        //         // npm build, 'sh' specifies it is a shell command
        //         bat """
        //             cd backend
        //             npm i && npm test
        //         """.stripIndent().trim()
        //     }
        // }
        stage('Build Docker Images') {
             steps {
                bat """
                cd backend
                docker build -t gramophone/gramophone_backend:latest
                """.stripIndent().trim()
             }
        }

        stage('Publish Docker Images') {
            steps {
                withDockerRegistry([ credentialsId: "DockerJenkins", url: "" ]) {
                    sh 'docker push premsai1503/majorProject_backend:latest'
                }
            }
        }
        stage('Clean Docker Images') {
            steps {
               sh 'docker rmi -f premsai1503/majorProject_backend:latest'
            }
        }
        stage('Deploy and Run Image') {
            steps {
                ansiblePlaybook becomeUser: null, colorized: true, disableHostKeyChecking: true, installation: 'Ansible', inventory: './ansible/inventory', playbook: './ansible/playbook.yml', sudoUser: null
            }
        }
    }
      post {
            always {
                sh 'docker logout'
            }
        }
}
